[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "cmake>=3.10",
    "packaging",
    "setuptools>=42",
    "wheel",
    "pytest",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
rtxpy = ["*.ptx", "*.so"]
